export const ROLE_KEYS = Object.freeze({
  AUDITOR: 'AUDITOR',
  SUPERVISOR: 'SUPERVISOR',
  ADMIN: 'ADMIN',
});

export const PERMISSIONS = Object.freeze({
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_TRANSACTIONS: 'VIEW_TRANSACTIONS',
  REVIEW_TRANSACTIONS: 'REVIEW_TRANSACTIONS',
  VIEW_ALERTS: 'VIEW_ALERTS',
  REVIEW_ALERTS: 'REVIEW_ALERTS',
  VIEW_AUDIT_RULES: 'VIEW_AUDIT_RULES',
  VIEW_REPORTS: 'VIEW_REPORTS',
  VIEW_TEAM_ACTIVITY: 'VIEW_TEAM_ACTIVITY',
  ASSIGN_ALERTS: 'ASSIGN_ALERTS',
  VIEW_AUDIT_LOG: 'VIEW_AUDIT_LOG',
  MANAGE_USERS: 'MANAGE_USERS',
  UNLOCK_USERS: 'UNLOCK_USERS',
  CHANGE_USER_ROLES: 'CHANGE_USER_ROLES',
  VIEW_SETTINGS: 'VIEW_SETTINGS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  VIEW_OWN_PROFILE: 'VIEW_OWN_PROFILE',
  VIEW_CASES: 'VIEW_CASES',
  CREATE_CASE: 'CREATE_CASE',
  ASSIGN_CASE: 'ASSIGN_CASE',
  UPDATE_ASSIGNED_CASE: 'UPDATE_ASSIGNED_CASE',
  REQUEST_CASE_CLOSURE: 'REQUEST_CASE_CLOSURE',
  APPROVE_CASE_CLOSURE: 'APPROVE_CASE_CLOSURE',
  ESCALATE_CASE: 'ESCALATE_CASE',
  VIEW_VENDORS: 'VIEW_VENDORS',
  REQUEST_VENDOR_WATCHLIST: 'REQUEST_VENDOR_WATCHLIST',
  REVIEW_VENDOR_WATCHLIST_REQUEST: 'REVIEW_VENDOR_WATCHLIST_REQUEST',
  REQUEST_VENDOR_BLOCK: 'REQUEST_VENDOR_BLOCK',
  MANAGE_VENDOR_BLOCK: 'MANAGE_VENDOR_BLOCK',
  REMOVE_VENDOR_WATCHLIST: 'REMOVE_VENDOR_WATCHLIST',
});

const auditorPermissions = Object.freeze([
  PERMISSIONS.VIEW_DASHBOARD,
  PERMISSIONS.VIEW_TRANSACTIONS,
  PERMISSIONS.REVIEW_TRANSACTIONS,
  PERMISSIONS.VIEW_ALERTS,
  PERMISSIONS.REVIEW_ALERTS,
  PERMISSIONS.VIEW_AUDIT_RULES,
  PERMISSIONS.VIEW_OWN_PROFILE,
  PERMISSIONS.VIEW_CASES,
  PERMISSIONS.CREATE_CASE,
  PERMISSIONS.UPDATE_ASSIGNED_CASE,
  PERMISSIONS.REQUEST_CASE_CLOSURE,
  PERMISSIONS.ESCALATE_CASE,
  PERMISSIONS.VIEW_VENDORS,
  PERMISSIONS.REQUEST_VENDOR_WATCHLIST,
]);

const supervisorPermissions = Object.freeze([
  ...auditorPermissions.filter((permission) => permission !== PERMISSIONS.REQUEST_CASE_CLOSURE),
  PERMISSIONS.VIEW_REPORTS,
  PERMISSIONS.VIEW_TEAM_ACTIVITY,
  PERMISSIONS.ASSIGN_ALERTS,
  PERMISSIONS.ASSIGN_CASE,
  PERMISSIONS.VIEW_AUDIT_LOG,
  PERMISSIONS.APPROVE_CASE_CLOSURE,
  PERMISSIONS.REVIEW_VENDOR_WATCHLIST_REQUEST,
  PERMISSIONS.REMOVE_VENDOR_WATCHLIST,
  PERMISSIONS.REQUEST_VENDOR_BLOCK,
]);

export const ROLE_DEFINITIONS = Object.freeze({
  [ROLE_KEYS.AUDITOR]: Object.freeze({
    key: ROLE_KEYS.AUDITOR,
    displayName: 'Auditor',
    description: 'Reviews transactions, alerts, and audit-rule findings.',
  }),
  [ROLE_KEYS.SUPERVISOR]: Object.freeze({
    key: ROLE_KEYS.SUPERVISOR,
    displayName: 'Supervisor',
    description: 'Oversees audit work, reporting, assignments, and team activity.',
  }),
  [ROLE_KEYS.ADMIN]: Object.freeze({
    key: ROLE_KEYS.ADMIN,
    displayName: 'Administrator',
    description: 'Manages system access, users, roles, and configuration.',
  }),
});

export const ROLE_PERMISSION_MAP = Object.freeze({
  [ROLE_KEYS.AUDITOR]: auditorPermissions,
  [ROLE_KEYS.SUPERVISOR]: supervisorPermissions,
  [ROLE_KEYS.ADMIN]: Object.freeze(Object.values(PERMISSIONS).filter((permission) => ![
    PERMISSIONS.REQUEST_CASE_CLOSURE,
    PERMISSIONS.REQUEST_VENDOR_WATCHLIST,
    PERMISSIONS.REVIEW_VENDOR_WATCHLIST_REQUEST,
    PERMISSIONS.REQUEST_VENDOR_BLOCK,
  ].includes(permission))),
});

export function getRoleDefinition(role) {
  return ROLE_DEFINITIONS[role] ?? null;
}

export function getPermissionsForRole(role) {
  return [...(ROLE_PERMISSION_MAP[role] ?? [])];
}

export function hasPermission(role, permission) {
  return ROLE_PERMISSION_MAP[role]?.includes(permission) ?? false;
}
