export const USER_LIFECYCLE_STATES = Object.freeze({
  REQUESTED: 'REQUESTED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
});

export const USER_LIFECYCLE_SEQUENCE = Object.freeze([
  USER_LIFECYCLE_STATES.REQUESTED,
  USER_LIFECYCLE_STATES.PENDING_APPROVAL,
  USER_LIFECYCLE_STATES.APPROVED,
  USER_LIFECYCLE_STATES.ACTIVE,
]);
