import { useState } from 'react';
import { AUDIT_COVERAGE_RULES, createAuditCoverage, createTrendModel } from '../analytics/analyticsModels.js';

function ChartEmpty({ title, description }) {
  return <div className="chart-empty-state" role="status"><div className="chart-empty-visual" aria-hidden="true"><i /><i /><i /><i /><i /></div><h3>{title}</h3><p>{description}</p></div>;
}

function PeriodSelect({ id, value, onChange }) {
  return <label className="analytics-period"><span>Period</span><select id={id} value={value} onChange={(event) => onChange(event.target.value)}><option value="7_DAYS">7 days</option><option value="30_DAYS">30 days</option><option value="90_DAYS">90 days</option></select></label>;
}

export default function AuditAnalytics() {
  const coverage = createAuditCoverage();
  const [riskPeriod, setRiskPeriod] = useState(createTrendModel().period);
  const [rulePeriod, setRulePeriod] = useState(createTrendModel().period);
  return <section className="report-analytics" aria-labelledby="audit-analytics-heading"><div className="report-section-header"><div><span className="report-section-eyebrow">Assurance analytics</span><h2 id="audit-analytics-heading">Audit Coverage &amp; Risk Trends</h2><p>Authoritative coverage and time-series views will appear as analytics services become available.</p></div></div><section className="card analytics-card" aria-labelledby="coverage-heading"><div className="analytics-card-header"><div><h3 id="coverage-heading">Audit Coverage</h3><p>Completeness of transaction evaluation across required audit controls.</p></div><strong className="coverage-value" aria-label="Coverage percentage unavailable">—</strong></div><div className="analytics-metrics">{[['Total Transactions', coverage.totalTransactions], ['Fully Evaluated', coverage.fullyEvaluated], ['Partially Evaluated', coverage.partiallyEvaluated], ['Not Evaluated', coverage.notEvaluated]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value ?? '—'}</strong></div>)}</div><div className="coverage-table-wrap"><table className="operations-table"><caption>Coverage by Rule</caption><thead><tr><th>Audit Rule</th><th>Eligible Transactions</th><th>Evaluated</th><th>Not Evaluated</th><th>Coverage</th></tr></thead><tbody>{AUDIT_COVERAGE_RULES.map((rule) => <tr key={rule}><th scope="row">{rule}</th><td data-label="Eligible Transactions">—</td><td data-label="Evaluated">—</td><td data-label="Not Evaluated">—</td><td data-label="Coverage">—</td></tr>)}</tbody></table></div><aside className="coverage-exclusions"><h4>Why transactions were not fully evaluated</h4><p>No authoritative coverage exclusions are available yet.</p></aside></section><div className="analytics-grid"><section className="card analytics-card" aria-labelledby="risk-trend-heading"><div className="analytics-card-header"><div><h3 id="risk-trend-heading">Risk Trend</h3><p>Average risk, high-risk transactions, alerts, confirmed issues, and false positives.</p></div><PeriodSelect id="risk-period" value={riskPeriod} onChange={setRiskPeriod} /></div><ChartEmpty title="Risk trend data is not available yet." description="No time-series values have been supplied by the analytics service." /></section><section className="card analytics-card" aria-labelledby="rule-trend-heading"><div className="analytics-card-header"><div><h3 id="rule-trend-heading">Violations by Rule Over Time</h3><p>Trend view for the five project audit rules.</p></div><PeriodSelect id="rule-period" value={rulePeriod} onChange={setRulePeriod} /></div><ChartEmpty title="Rule trend data is not available yet." description="No rule-violation time series has been supplied by the analytics service." /></section></div></section>;
}
