import { useRef, useState } from 'react';
import useOverlayFocus from '../accessibility/useOverlayFocus.js';
import { REVIEW_RESOLUTIONS } from '../cases/caseWorkflow.js';

export default function CaseClosureDialog({ open, mode = 'request', caseRecord, busy = false, error = null, onSubmit, onClose }) {
  const dialogRef = useRef(null); const backdropRef = useRef(null); const cancelRef = useRef(null);
  const [outcome, setOutcome] = useState(''); const [note, setNote] = useState(''); const [evidenceSummary, setEvidenceSummary] = useState('');
  useOverlayFocus({ active: open, containerRef: dialogRef, boundaryRef: backdropRef, initialFocusRef: cancelRef, onEscape: onClose });
  if (!open) return null;
  const approving = mode === 'approve';
  const submit = (event) => { event.preventDefault(); onSubmit?.(approving ? { approve: event.nativeEvent.submitter?.value === 'approve', note: note || null } : { outcome, note, evidence_summary: evidenceSummary || null }); };
  return <div ref={backdropRef} className="dialog-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && !busy && onClose()}><section ref={dialogRef} tabIndex="-1" className="management-dialog case-closure-dialog" role="dialog" aria-modal="true" aria-labelledby="case-closure-title"><span className="page-eyebrow">Controlled case workflow</span><h2 id="case-closure-title">{approving ? 'Review Closure Request' : 'Request Closure'}</h2><p>{approving ? 'Review the resolution, then approve closure or return the case to investigation.' : 'Submit a resolution for an independent Supervisor or Admin decision. The requester cannot decide their own request.'}</p>
    {approving && <dl className="workflow-confirmation-details"><div><dt>Requested By</dt><dd>{caseRecord?.closureRequestedBy ?? '—'}</dd></div><div><dt>Requested At</dt><dd>{caseRecord?.closureRequestedAt ?? '—'}</dd></div><div><dt>Resolution</dt><dd>{caseRecord?.resolution ?? '—'}</dd></div><div><dt>Evidence</dt><dd>{caseRecord?.evidenceSummary ?? '—'}</dd></div><div><dt>Notes</dt><dd>{caseRecord?.resolutionNote ?? '—'}</dd></div></dl>}
    <form onSubmit={submit}>{!approving && <label className="dialog-field"><span>Resolution</span><select required value={outcome} onChange={(event) => setOutcome(event.target.value)}><option value="" disabled>Select resolution</option>{Object.values(REVIEW_RESOLUTIONS).map((value) => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></label>}<label className="dialog-field"><span>{approving ? 'Decision note (optional)' : 'Resolution note'}</span><textarea required={!approving} rows="4" maxLength={4000} value={note} onChange={(event) => setNote(event.target.value)} /></label>{!approving && <label className="dialog-field"><span>Evidence summary (optional)</span><textarea rows="3" maxLength={2000} value={evidenceSummary} onChange={(event) => setEvidenceSummary(event.target.value)} /></label>}{error && <p role="alert" className="integration-note">{error}</p>}<div className="dialog-actions"><button ref={cancelRef} type="button" className="btn btn-secondary" onClick={onClose} disabled={busy}>Cancel</button>{approving && <button type="submit" name="decision" value="reject" className="btn btn-secondary" disabled={busy}>Return for Investigation</button>}<button type="submit" name="decision" value="approve" className="btn btn-primary" disabled={busy || (!approving && (!outcome || !note.trim()))}>{busy ? 'Saving…' : approving ? 'Approve Closure' : 'Submit Closure Request'}</button></div></form>
  </section></div>;
}
